[package]
name = "sdl_rust"
version = "0.1.0"
authors = ["John Pangalos <jpangs88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.sdl2]
version = "0.34"
# default-features = false
# features = ["ttf","image","gfx","mixer"]
